name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey welcome to the Repo and conragulation on your first issue in this repo 🥳🥳"
        pr-message: "Hey welcome to the Repo and conragulation on your first PR in this repo 🥳🥳
